var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/doctor/consultation/[appointmentId]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gyy232._.js")
R.c("server/chunks/ssr/0yz0_next_dist_1a-4c9q._.js")
R.c("server/chunks/ssr/0yz0_next_dist_esm_build_templates_app-page_1clbleg.js")
R.c("server/chunks/ssr/[root-of-the-server]__14g52h1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03qfu_z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__08g6l4k._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_0a70a9d._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_0e9exsp._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_builtin_unauthorized_18vk5b5.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_app_global-error_tsx_1n68bqr._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_app_doctor_layout_tsx_0iz7d9m._.js")
R.c("server/chunks/ssr/0_f0_server_app_doctor_consultation_[appointmentId]_page_actions_1t5u6k6.js")
R.m(74622)
module.exports=R.m(74622).exports
