var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/hospital/departments/pharmacy/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__13-z7p1._.js")
R.c("server/chunks/ssr/0yz0_next_dist_1a-4c9q._.js")
R.c("server/chunks/ssr/0yz0_next_dist_esm_build_templates_app-page_1wdssu8.js")
R.c("server/chunks/ssr/[root-of-the-server]__14g52h1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03qfu_z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__08g6l4k._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_0a70a9d._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_0e9exsp._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_builtin_unauthorized_18vk5b5.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_app_global-error_tsx_1n68bqr._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_0o70gfr._.js")
R.c("server/chunks/ssr/06tw__next-internal_server_app_hospital_departments_pharmacy_page_actions_1nfcx7l.js")
R.m(9550)
module.exports=R.m(9550).exports
