// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/admin/audit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/audit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admin/audit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/admissions/allocate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admissions/allocate">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admissions/allocate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/assets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assets">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/assets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emergency">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/finance">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/insurance-tpa/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insurance-tpa">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/insurance-tpa/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ipd-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ipd-management">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ipd-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ipd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ipd">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ipd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/lab/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/lab/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/master-data/pharmacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data/pharmacy">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/master-data/pharmacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/opd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/opd">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/opd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/ot-coordination/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ot-coordination">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/ot-coordination/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/patients/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patients/register">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/patients/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/pharmacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pharmacy">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/pharmacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/procurement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/procurement">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/procurement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/staff/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/roles">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/staff/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/vendor-coordination/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor-coordination">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/vendor-coordination/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/onboarding">> = Specific
  const handler = {} as typeof import("../../app/admin/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/appointments">> = Specific
  const handler = {} as typeof import("../../app/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/clinical-suite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/clinical-suite">> = Specific
  const handler = {} as typeof import("../../app/clinical-suite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/compliance-contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance-contracts">> = Specific
  const handler = {} as typeof import("../../app/compliance-contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/consultation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/consultation">> = Specific
  const handler = {} as typeof import("../../app/consultation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/admissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/admissions">> = Specific
  const handler = {} as typeof import("../../app/dashboard/admissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/appointments">> = Specific
  const handler = {} as typeof import("../../app/dashboard/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/clinical-suite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/clinical-suite">> = Specific
  const handler = {} as typeof import("../../app/dashboard/clinical-suite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/consultation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/consultation">> = Specific
  const handler = {} as typeof import("../../app/dashboard/consultation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/credentials">> = Specific
  const handler = {} as typeof import("../../app/dashboard/credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/documents">> = Specific
  const handler = {} as typeof import("../../app/dashboard/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/emr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/emr">> = Specific
  const handler = {} as typeof import("../../app/dashboard/emr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/hospital/finance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/hospital/finance">> = Specific
  const handler = {} as typeof import("../../app/dashboard/hospital/finance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/hospital/procurement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/hospital/procurement">> = Specific
  const handler = {} as typeof import("../../app/dashboard/hospital/procurement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inventory">> = Specific
  const handler = {} as typeof import("../../app/dashboard/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/ipd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/ipd">> = Specific
  const handler = {} as typeof import("../../app/dashboard/ipd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/laboratory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/laboratory">> = Specific
  const handler = {} as typeof import("../../app/dashboard/laboratory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/messaging/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messaging">> = Specific
  const handler = {} as typeof import("../../app/dashboard/messaging/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/notifications">> = Specific
  const handler = {} as typeof import("../../app/dashboard/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/opd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/opd">> = Specific
  const handler = {} as typeof import("../../app/dashboard/opd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/patients">> = Specific
  const handler = {} as typeof import("../../app/dashboard/patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/practice-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/practice-hub">> = Specific
  const handler = {} as typeof import("../../app/dashboard/practice-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/prescription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/prescription">> = Specific
  const handler = {} as typeof import("../../app/dashboard/prescription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/radiology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/radiology">> = Specific
  const handler = {} as typeof import("../../app/dashboard/radiology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/records">> = Specific
  const handler = {} as typeof import("../../app/dashboard/records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/smartq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/smartq">> = Specific
  const handler = {} as typeof import("../../app/dashboard/smartq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff-credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/staff-credentials">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff-credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/supply/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/supply">> = Specific
  const handler = {} as typeof import("../../app/dashboard/supply/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/surgery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/surgery">> = Specific
  const handler = {} as typeof import("../../app/dashboard/surgery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/telemedicine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/telemedicine">> = Specific
  const handler = {} as typeof import("../../app/dashboard/telemedicine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/vendors">> = Specific
  const handler = {} as typeof import("../../app/dashboard/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/display-board/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/display-board">> = Specific
  const handler = {} as typeof import("../../app/display-board/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/availability">> = Specific
  const handler = {} as typeof import("../../app/doctor/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/consultation/[appointmentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/consultation/[appointmentId]">> = Specific
  const handler = {} as typeof import("../../app/doctor/consultation/[appointmentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/consultations/[appointmentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/consultations/[appointmentId]">> = Specific
  const handler = {} as typeof import("../../app/doctor/consultations/[appointmentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/consultations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/consultations">> = Specific
  const handler = {} as typeof import("../../app/doctor/consultations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/dashboard">> = Specific
  const handler = {} as typeof import("../../app/doctor/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/emergency">> = Specific
  const handler = {} as typeof import("../../app/doctor/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/login">> = Specific
  const handler = {} as typeof import("../../app/doctor/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/messages">> = Specific
  const handler = {} as typeof import("../../app/doctor/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor">> = Specific
  const handler = {} as typeof import("../../app/doctor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/patients/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/patients/[id]">> = Specific
  const handler = {} as typeof import("../../app/doctor/patients/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/patients">> = Specific
  const handler = {} as typeof import("../../app/doctor/patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/profile">> = Specific
  const handler = {} as typeof import("../../app/doctor/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/queue">> = Specific
  const handler = {} as typeof import("../../app/doctor/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/records">> = Specific
  const handler = {} as typeof import("../../app/doctor/records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/schedule">> = Specific
  const handler = {} as typeof import("../../app/doctor/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/doctor/workspace">> = Specific
  const handler = {} as typeof import("../../app/doctor/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents">> = Specific
  const handler = {} as typeof import("../../app/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/emr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/emr">> = Specific
  const handler = {} as typeof import("../../app/emr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/entrepreneur/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entrepreneur/dashboard">> = Specific
  const handler = {} as typeof import("../../app/entrepreneur/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/entrepreneur/opd-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/entrepreneur/opd-analytics">> = Specific
  const handler = {} as typeof import("../../app/entrepreneur/opd-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/admissions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/admissions">> = Specific
  const handler = {} as typeof import("../../app/hospital/admissions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/appointments">> = Specific
  const handler = {} as typeof import("../../app/hospital/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/admission-charges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/admission-charges">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/admission-charges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/invoices">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/lab-charges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/lab-charges">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/lab-charges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/medicine-charges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/medicine-charges">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/medicine-charges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/opd-charges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/opd-charges">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/opd-charges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/ot-charges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/ot-charges">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/ot-charges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/radiology-charges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/radiology-charges">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/radiology-charges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/billing/receipts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/billing/receipts">> = Specific
  const handler = {} as typeof import("../../app/hospital/billing/receipts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/core-operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/core-operations">> = Specific
  const handler = {} as typeof import("../../app/hospital/core-operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/dashboard">> = Specific
  const handler = {} as typeof import("../../app/hospital/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/departments/emr-vault/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/departments/emr-vault">> = Specific
  const handler = {} as typeof import("../../app/hospital/departments/emr-vault/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/departments/laboratory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/departments/laboratory">> = Specific
  const handler = {} as typeof import("../../app/hospital/departments/laboratory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/departments/opd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/departments/opd">> = Specific
  const handler = {} as typeof import("../../app/hospital/departments/opd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/departments/pharmacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/departments/pharmacy">> = Specific
  const handler = {} as typeof import("../../app/hospital/departments/pharmacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/departments/radiology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/departments/radiology">> = Specific
  const handler = {} as typeof import("../../app/hospital/departments/radiology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/discharge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/discharge">> = Specific
  const handler = {} as typeof import("../../app/hospital/discharge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/emergency">> = Specific
  const handler = {} as typeof import("../../app/hospital/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/emr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/emr">> = Specific
  const handler = {} as typeof import("../../app/hospital/emr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/insurance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/insurance">> = Specific
  const handler = {} as typeof import("../../app/hospital/insurance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/inventory">> = Specific
  const handler = {} as typeof import("../../app/hospital/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/ipd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/ipd">> = Specific
  const handler = {} as typeof import("../../app/hospital/ipd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/laboratory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/laboratory">> = Specific
  const handler = {} as typeof import("../../app/hospital/laboratory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/login">> = Specific
  const handler = {} as typeof import("../../app/hospital/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/notifications">> = Specific
  const handler = {} as typeof import("../../app/hospital/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/opd-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/opd-queue">> = Specific
  const handler = {} as typeof import("../../app/hospital/opd-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/opd-reception/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/opd-reception">> = Specific
  const handler = {} as typeof import("../../app/hospital/opd-reception/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/opd/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/opd">> = Specific
  const handler = {} as typeof import("../../app/hospital/opd/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/operations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/operations">> = Specific
  const handler = {} as typeof import("../../app/hospital/operations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/ot/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/ot">> = Specific
  const handler = {} as typeof import("../../app/hospital/ot/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital">> = Specific
  const handler = {} as typeof import("../../app/hospital/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/patients">> = Specific
  const handler = {} as typeof import("../../app/hospital/patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/patients/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/patients/register">> = Specific
  const handler = {} as typeof import("../../app/hospital/patients/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/payments">> = Specific
  const handler = {} as typeof import("../../app/hospital/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/pharmacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/pharmacy">> = Specific
  const handler = {} as typeof import("../../app/hospital/pharmacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/radiology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/radiology">> = Specific
  const handler = {} as typeof import("../../app/hospital/radiology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/reception/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/reception">> = Specific
  const handler = {} as typeof import("../../app/hospital/reception/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/security">> = Specific
  const handler = {} as typeof import("../../app/hospital/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/settings">> = Specific
  const handler = {} as typeof import("../../app/hospital/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/setup">> = Specific
  const handler = {} as typeof import("../../app/hospital/setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/staff-credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/staff-credentials">> = Specific
  const handler = {} as typeof import("../../app/hospital/staff-credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/staff/attendance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/staff/attendance">> = Specific
  const handler = {} as typeof import("../../app/hospital/staff/attendance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/staff/departments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/staff/departments">> = Specific
  const handler = {} as typeof import("../../app/hospital/staff/departments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/staff/employees/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/staff/employees">> = Specific
  const handler = {} as typeof import("../../app/hospital/staff/employees/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/staff">> = Specific
  const handler = {} as typeof import("../../app/hospital/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/staff/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/staff/roles">> = Specific
  const handler = {} as typeof import("../../app/hospital/staff/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/staff/shifts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/staff/shifts">> = Specific
  const handler = {} as typeof import("../../app/hospital/staff/shifts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/vendors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hospital/vendors">> = Specific
  const handler = {} as typeof import("../../app/hospital/vendors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/laboratory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laboratory">> = Specific
  const handler = {} as typeof import("../../app/laboratory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/login/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/reset-password">> = Specific
  const handler = {} as typeof import("../../app/login/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/master-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/master-data">> = Specific
  const handler = {} as typeof import("../../app/master-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/messaging/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messaging">> = Specific
  const handler = {} as typeof import("../../app/messaging/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ops/platform-root/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ops/platform-root">> = Specific
  const handler = {} as typeof import("../../app/ops/platform-root/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/appointments/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/appointments/book">> = Specific
  const handler = {} as typeof import("../../app/patient/appointments/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/appointments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/appointments">> = Specific
  const handler = {} as typeof import("../../app/patient/appointments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/auth/login">> = Specific
  const handler = {} as typeof import("../../app/patient/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/billing">> = Specific
  const handler = {} as typeof import("../../app/patient/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/book/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/book">> = Specific
  const handler = {} as typeof import("../../app/patient/book/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/care-plan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/care-plan">> = Specific
  const handler = {} as typeof import("../../app/patient/care-plan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/communication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/communication">> = Specific
  const handler = {} as typeof import("../../app/patient/communication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/dashboard">> = Specific
  const handler = {} as typeof import("../../app/patient/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/diagnostics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/diagnostics">> = Specific
  const handler = {} as typeof import("../../app/patient/diagnostics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/doctors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/doctors">> = Specific
  const handler = {} as typeof import("../../app/patient/doctors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/emergency/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/emergency">> = Specific
  const handler = {} as typeof import("../../app/patient/emergency/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/health">> = Specific
  const handler = {} as typeof import("../../app/patient/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/insurance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/insurance">> = Specific
  const handler = {} as typeof import("../../app/patient/insurance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/login">> = Specific
  const handler = {} as typeof import("../../app/patient/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/medical-records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/medical-records">> = Specific
  const handler = {} as typeof import("../../app/patient/medical-records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/medications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/medications">> = Specific
  const handler = {} as typeof import("../../app/patient/medications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/messages">> = Specific
  const handler = {} as typeof import("../../app/patient/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/notifications">> = Specific
  const handler = {} as typeof import("../../app/patient/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient">> = Specific
  const handler = {} as typeof import("../../app/patient/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/portal">> = Specific
  const handler = {} as typeof import("../../app/patient/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/prescriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/prescriptions">> = Specific
  const handler = {} as typeof import("../../app/patient/prescriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/profile">> = Specific
  const handler = {} as typeof import("../../app/patient/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/queue">> = Specific
  const handler = {} as typeof import("../../app/patient/queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/records/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/records">> = Specific
  const handler = {} as typeof import("../../app/patient/records/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/register">> = Specific
  const handler = {} as typeof import("../../app/patient/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/settings">> = Specific
  const handler = {} as typeof import("../../app/patient/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/teleconsult/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/teleconsult">> = Specific
  const handler = {} as typeof import("../../app/patient/teleconsult/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/telemedicine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patient/telemedicine">> = Specific
  const handler = {} as typeof import("../../app/patient/telemedicine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patients/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patients">> = Specific
  const handler = {} as typeof import("../../app/patients/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/platform-ops-x92/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/platform-ops-x92/auth">> = Specific
  const handler = {} as typeof import("../../app/platform-ops-x92/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/practice-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/practice-hub">> = Specific
  const handler = {} as typeof import("../../app/practice-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/prescription/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prescription">> = Specific
  const handler = {} as typeof import("../../app/prescription/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase-orders">> = Specific
  const handler = {} as typeof import("../../app/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/radiology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/radiology">> = Specific
  const handler = {} as typeof import("../../app/radiology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/service-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/service-requests">> = Specific
  const handler = {} as typeof import("../../app/service-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/staff/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/login">> = Specific
  const handler = {} as typeof import("../../app/staff/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/staff/nursing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/nursing">> = Specific
  const handler = {} as typeof import("../../app/staff/nursing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/staff/pharmacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/pharmacy">> = Specific
  const handler = {} as typeof import("../../app/staff/pharmacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/staff/reception/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/staff/reception">> = Specific
  const handler = {} as typeof import("../../app/staff/reception/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/dashboard">> = Specific
  const handler = {} as typeof import("../../app/super-admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-admin/staff-credentials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/staff-credentials">> = Specific
  const handler = {} as typeof import("../../app/super-admin/staff-credentials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-admin/tenants/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/tenants/[id]">> = Specific
  const handler = {} as typeof import("../../app/super-admin/tenants/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-admin/tenants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin/tenants">> = Specific
  const handler = {} as typeof import("../../app/super-admin/tenants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-vault-access/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-vault-access/[id]">> = Specific
  const handler = {} as typeof import("../../app/super-vault-access/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-vault-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-vault-access">> = Specific
  const handler = {} as typeof import("../../app/super-vault-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/superadmin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/superadmin/login">> = Specific
  const handler = {} as typeof import("../../app/superadmin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/surgery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/surgery">> = Specific
  const handler = {} as typeof import("../../app/surgery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/telemedicine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/telemedicine">> = Specific
  const handler = {} as typeof import("../../app/telemedicine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/hospital/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/hospital">> = Specific
  const handler = {} as typeof import("../../app/vendor/hospital/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/login">> = Specific
  const handler = {} as typeof import("../../app/vendor/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor">> = Specific
  const handler = {} as typeof import("../../app/vendor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/analytics">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/billing">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/catalog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/catalog">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/catalog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/communication/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/communication">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/communication/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/compliance">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/contracts">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/dashboard">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/deliveries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/deliveries">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/deliveries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/inventory">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/invoices/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/invoices">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/invoices/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/notifications">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/orders">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/organization">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/purchase-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/purchase-orders">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/purchase-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/quotations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/quotations">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/quotations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/service-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/service-requests">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/service-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/settings">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/support">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/warehouse">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal/login">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/portal">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/secure-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/secure-hub">> = Specific
  const handler = {} as typeof import("../../app/vendor/secure-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/secure-hub/po-inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/secure-hub/po-inbox">> = Specific
  const handler = {} as typeof import("../../app/vendor/secure-hub/po-inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vendor/workspace">> = Specific
  const handler = {} as typeof import("../../app/vendor/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/appointments/check-in/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/appointments/check-in">> = Specific
  const handler = {} as typeof import("../../app/api/appointments/check-in/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctor/auth/clinician-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctor/auth/clinician-login">> = Specific
  const handler = {} as typeof import("../../app/api/doctor/auth/clinician-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/doctor/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/doctor/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/doctor/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/emergency/triage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emergency/triage">> = Specific
  const handler = {} as typeof import("../../app/api/emergency/triage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/hospital/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hospital/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/hospital/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ipd/admit-transfer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ipd/admit-transfer">> = Specific
  const handler = {} as typeof import("../../app/api/ipd/admit-transfer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/patient/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/patient/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/patient/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pharmacy/dispense/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pharmacy/dispense">> = Specific
  const handler = {} as typeof import("../../app/api/pharmacy/dispense/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/procurement/create-po/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/procurement/create-po">> = Specific
  const handler = {} as typeof import("../../app/api/procurement/create-po/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/queue/arrive/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/arrive">> = Specific
  const handler = {} as typeof import("../../app/api/queue/arrive/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/queue/next/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/queue/next">> = Specific
  const handler = {} as typeof import("../../app/api/queue/next/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/super-admin/staff/[staffId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/super-admin/staff/[staffId]">> = Specific
  const handler = {} as typeof import("../../app/api/super-admin/staff/[staffId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/super-admin/tenants/[hospitalId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/super-admin/tenants/[hospitalId]">> = Specific
  const handler = {} as typeof import("../../app/api/super-admin/tenants/[hospitalId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/super-vault/unlock/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/super-vault/unlock">> = Specific
  const handler = {} as typeof import("../../app/api/super-vault/unlock/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/master-data/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/master-data">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/master-data/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/staff/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/staff">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/staff/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/staff-credentials/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard/staff-credentials">> = Specific
  const handler = {} as typeof import("../../app/dashboard/staff-credentials/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/doctor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/doctor">> = Specific
  const handler = {} as typeof import("../../app/doctor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hospital/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/hospital">> = Specific
  const handler = {} as typeof import("../../app/hospital/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/patient/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/patient">> = Specific
  const handler = {} as typeof import("../../app/patient/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../app/super-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/super-vault-access/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/super-vault-access">> = Specific
  const handler = {} as typeof import("../../app/super-vault-access/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/vendor">> = Specific
  const handler = {} as typeof import("../../app/vendor/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/(shell)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/vendor/portal">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/(shell)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vendor/portal/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/vendor/portal">> = Specific
  const handler = {} as typeof import("../../app/vendor/portal/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
