var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/documents/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1dw-zz2._.js")
R.c("server/chunks/ssr/0yz0_next_dist_1a-4c9q._.js")
R.c("server/chunks/ssr/0yz0_next_dist_esm_build_templates_app-page_0o5t1bw.js")
R.c("server/chunks/ssr/[root-of-the-server]__14g52h1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03qfu_z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__08g6l4k._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_0a70a9d._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_0e9exsp._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_builtin_unauthorized_18vk5b5.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_app_global-error_tsx_1n68bqr._.js")
R.c("server/chunks/ssr/1fmp_caresync_curasync__next-internal_server_app_documents_page_actions_18pgopo.js")
R.m(882719)
module.exports=R.m(882719).exports
