/**
 * Rich initialization / fallback datasets for Regal Hospital Operations Center.
 * Screens stay fully populated even when Supabase tables are empty.
 */

import { regalDoctorsAsStaffRows } from '@/components/nexora-hospital/regal-doctors';

export { REGAL_DOCTORS, DEFAULT_REGAL_DOCTOR, findRegalDoctor } from '@/components/nexora-hospital/regal-doctors';

export const REGAL_FACILITY = {
  name: 'Regal Hospital',
  code: 'RH-BLR-01',
  node: 'REGAL-CORE-NODE-01',
  tagline: 'Enterprise Clinical Operations & Realtime Command Center',
} as const;

export const REGAL_KPI_DEFAULTS = {
  opdToday: 128,
  opdWaiting: 32,
  bedsOccupied: 74,
  bedsTotal: 90,
  emergencyActive: 6,
  emergencyP1: 2,
  revenueLakhs: 4.85,
  revenueDeltaPct: 14,
  ancillaryQueue: 42,
  pharmacyRx: 24,
  labTests: 18,
  radiologyScans: 9,
  supplyInTransit: 3,
  lowStock: 5,
  rxPending: 14,
} as const;

export const SEED_PATIENTS = [
  {
    id: 'pt-001',
    uhid: 'RH-2026-001245',
    full_name: 'Ananya Krishnan',
    age: 34,
    gender: 'Female',
    blood_group: 'O+',
    phone: '+91 98765 41230',
    emergency_contact: 'Ravi Krishnan · +91 98765 41231',
    ward: 'Private Wing A · Bed 04',
    doctor: 'Dr. Meera Iyer',
    admission_status: 'IPD',
    insurance: 'Star Health · POL-8821',
    created_at: '2026-03-12T08:20:00Z',
  },
  {
    id: 'pt-002',
    uhid: 'RH-2026-001246',
    full_name: 'Vikram Sethi',
    age: 52,
    gender: 'Male',
    blood_group: 'B+',
    phone: '+91 98111 22001',
    emergency_contact: 'Neha Sethi · +91 98111 22002',
    ward: 'ICU Unit 1 · Bed 02',
    doctor: 'Dr. Arjun Rao',
    admission_status: 'ICU',
    insurance: 'ICICI Lombard · POL-4410',
    created_at: '2026-03-14T11:05:00Z',
  },
  {
    id: 'pt-003',
    uhid: 'RH-2026-001247',
    full_name: 'Fatima Begum',
    age: 28,
    gender: 'Female',
    blood_group: 'A+',
    phone: '+91 90000 11882',
    emergency_contact: 'Imran Begum · +91 90000 11883',
    ward: '—',
    doctor: 'Dr. Kavitha Nair',
    admission_status: 'OPD',
    insurance: 'Self-pay',
    created_at: '2026-03-15T07:40:00Z',
  },
  {
    id: 'pt-004',
    uhid: 'RH-2026-001248',
    full_name: 'Rohit Malhotra',
    age: 41,
    gender: 'Male',
    blood_group: 'AB+',
    phone: '+91 99887 66554',
    emergency_contact: 'Sonia Malhotra · +91 99887 66555',
    ward: 'General Male · Bed 12',
    doctor: 'Dr. Suresh Pillai',
    admission_status: 'IPD',
    insurance: 'HDFC Ergo · POL-2299',
    created_at: '2026-03-10T14:15:00Z',
  },
  {
    id: 'pt-005',
    uhid: 'RH-2026-001249',
    full_name: 'Priya Deshmukh',
    age: 19,
    gender: 'Female',
    blood_group: 'O-',
    phone: '+91 91234 56780',
    emergency_contact: 'Amit Deshmukh · +91 91234 56781',
    ward: '—',
    doctor: 'Dr. Neelima Joshi',
    admission_status: 'OPD',
    insurance: 'Self-pay',
    created_at: '2026-03-16T09:10:00Z',
  },
  {
    id: 'pt-006',
    uhid: 'RH-2026-001250',
    full_name: 'Karthik Venkatesh',
    age: 63,
    gender: 'Male',
    blood_group: 'A-',
    phone: '+91 97654 32100',
    emergency_contact: 'Lakshmi V · +91 97654 32101',
    ward: 'ICU Unit 1 · Bed 07',
    doctor: 'Dr. Arjun Rao',
    admission_status: 'ICU',
    insurance: 'Religare · POL-1102',
    created_at: '2026-03-15T22:30:00Z',
  },
  {
    id: 'pt-007',
    uhid: 'RH-2026-001251',
    full_name: 'Meena Kuppuswamy',
    age: 47,
    gender: 'Female',
    blood_group: 'B-',
    phone: '+91 95555 01010',
    emergency_contact: 'Kumar K · +91 95555 01011',
    ward: 'Private Wing A · Bed 11',
    doctor: 'Dr. Meera Iyer',
    admission_status: 'IPD',
    insurance: 'Star Health · POL-9910',
    created_at: '2026-03-13T16:45:00Z',
  },
  {
    id: 'pt-008',
    uhid: 'RH-2026-001252',
    full_name: 'Unknown Male (Trauma)',
    age: 35,
    gender: 'Male',
    blood_group: 'Unknown',
    phone: '—',
    emergency_contact: 'Police Control · 100',
    ward: 'ER Bay 1',
    doctor: 'Dr. Trauma Lead',
    admission_status: 'ER',
    insurance: 'Pending',
    created_at: '2026-03-17T05:12:00Z',
  },
];

export const SEED_APPOINTMENTS = [
  {
    id: 'ap-001',
    token_number: 'GS-024',
    uhid: 'RH-2026-001247',
    patient_name: 'Fatima Begum',
    doctor_name: 'Dr. Kavitha Nair',
    department: 'General Surgery',
    appointment_time: '09:20',
    priority: 'Normal',
    status: 'checked_in',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ap-002',
    token_number: 'CARD-012',
    uhid: 'RH-2026-001249',
    patient_name: 'Priya Deshmukh',
    doctor_name: 'Dr. Ananya Rao',
    department: 'Cardiology',
    appointment_time: '09:40',
    priority: 'Urgent',
    status: 'booked',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ap-003',
    token_number: 'OR-008',
    uhid: 'RH-2026-001253',
    patient_name: 'Sanjay Patil',
    doctor_name: 'Dr. Ramesh Kulkarni',
    department: 'Orthopedics',
    appointment_time: '10:00',
    priority: 'Normal',
    status: 'in_consultation',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ap-004',
    token_number: 'PD-003',
    uhid: 'RH-2026-001254',
    patient_name: 'Aarav Sharma',
    doctor_name: 'Dr. Softa Menon',
    department: 'Pediatrics',
    appointment_time: '10:15',
    priority: 'Normal',
    status: 'booked',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ap-005',
    token_number: 'ER-002',
    uhid: 'RH-2026-001252',
    patient_name: 'Unknown Male (Trauma)',
    doctor_name: 'Dr. Trauma Lead',
    department: 'Emergency',
    appointment_time: '05:12',
    priority: 'Critical',
    status: 'in_consultation',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ap-006',
    token_number: 'GS-025',
    uhid: 'RH-2026-001255',
    patient_name: 'Lakshmi Narayan',
    doctor_name: 'Dr. Kavitha Nair',
    department: 'General Surgery',
    appointment_time: '10:30',
    priority: 'Normal',
    status: 'booked',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ap-007',
    token_number: 'CD-012',
    uhid: 'RH-2026-001256',
    patient_name: 'Harish Gupta',
    doctor_name: 'Dr. Neelima Joshi',
    department: 'Cardiology',
    appointment_time: '11:00',
    priority: 'Normal',
    status: 'completed',
    created_at: new Date().toISOString(),
  },
  {
    id: 'ap-008',
    token_number: 'OR-009',
    uhid: 'RH-2026-001257',
    patient_name: 'Divya Reddy',
    doctor_name: 'Dr. Ramesh Kulkarni',
    department: 'Orthopedics',
    appointment_time: '11:20',
    priority: 'Urgent',
    status: 'checked_in',
    created_at: new Date().toISOString(),
  },
];

function bed(
  id: string,
  ward: string,
  bed_number: string,
  status: 'available' | 'occupied' | 'cleaning',
  patient_name?: string,
  doctor_name?: string,
) {
  return {
    id,
    ward,
    bed_number,
    status,
    is_occupied: status === 'occupied',
    patient_name,
    doctor_name,
  };
}

export const SEED_BEDS = [
  bed('ICU-01', 'ICU', '01', 'occupied', 'Vikram Sethi', 'Dr. Arjun Rao'),
  bed('ICU-02', 'ICU', '02', 'occupied', 'Karthik Venkatesh', 'Dr. Arjun Rao'),
  bed('ICU-03', 'ICU', '03', 'cleaning'),
  bed('ICU-04', 'ICU', '04', 'available'),
  bed('ICU-05', 'ICU', '05', 'occupied', 'Sunita Rajan', 'Dr. Trauma Lead'),
  bed('ICU-06', 'ICU', '06', 'available'),
  bed('ICU-07', 'ICU', '07', 'occupied', 'Imran Qureshi', 'Dr. Meera Iyer'),
  bed('ICU-08', 'ICU', '08', 'available'),
  bed('ICU-09', 'ICU', '09', 'occupied', 'Helen D\'Souza', 'Dr. Arjun Rao'),
  bed('ICU-10', 'ICU', '10', 'available'),
  ...Array.from({ length: 30 }, (_, i) => {
    const n = String(i + 1).padStart(2, '0');
    const occupied = i % 3 !== 0;
    const cleaning = i % 11 === 0;
    return bed(
      `GW-${n}`,
      'General Male Ward',
      n,
      cleaning ? 'cleaning' : occupied ? 'occupied' : 'available',
      occupied && !cleaning ? ['Rohit Malhotra', 'Ajay Nair', 'Balan P', 'Yusuf Ali', 'Prakash M'][i % 5] : undefined,
      occupied && !cleaning ? 'Dr. Suresh Pillai' : undefined,
    );
  }),
  ...Array.from({ length: 20 }, (_, i) => {
    const n = String(i + 1).padStart(2, '0');
    const occupied = i % 5 !== 0;
    return bed(
      `PR-${n}`,
      'Private Wing A',
      n,
      occupied ? 'occupied' : 'available',
      occupied ? ['Ananya Krishnan', 'Meena Kuppuswamy', 'Geetha R', 'Nisha V'][i % 4] : undefined,
      occupied ? 'Dr. Meera Iyer' : undefined,
    );
  }),
];

export const SEED_TRIAGES = [
  {
    id: 'tr-001',
    patient_name: 'Unknown Male (Trauma)',
    chief_complaint: 'RTA · head trauma · GCS 9',
    priority: 'P1',
    vitals: { bp: '90/60', spo2: '91', pulse: '128', rr: '28', gcs: '9', temp: '36.8' },
    status: 'active',
    surgeon: 'Dr. Trauma Lead',
    arrival: '05:12',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tr-002',
    patient_name: 'Kavya Menon',
    chief_complaint: 'Chest pain radiating to left arm',
    priority: 'P2',
    vitals: { bp: '150/95', spo2: '96', pulse: '102', rr: '22', gcs: '15', temp: '37.1' },
    status: 'active',
    surgeon: 'Dr. Neelima Joshi',
    arrival: '07:45',
    created_at: new Date().toISOString(),
  },
  {
    id: 'tr-003',
    patient_name: 'Arjun Das',
    chief_complaint: 'Ankle sprain · sports injury',
    priority: 'P3',
    vitals: { bp: '118/76', spo2: '99', pulse: '78', rr: '16', gcs: '15', temp: '36.6' },
    status: 'active',
    surgeon: 'Dr. Ramesh Kulkarni',
    arrival: '08:30',
    created_at: new Date().toISOString(),
  },
];

export const SEED_PRESCRIPTIONS = [
  {
    id: 'rx-001',
    patient_name: 'Fatima Begum',
    uhid: 'RH-2026-001247',
    doctor_name: 'Dr. Kavitha Nair',
    status: 'pending',
    is_dispensed: false,
    medications: [
      { name: 'Paracetamol 650mg', dosage: '650mg', frequency: 'TID', days: 5 },
      { name: 'Pantoprazole 40mg', dosage: '40mg', frequency: 'OD', days: 7 },
    ],
  },
  {
    id: 'rx-002',
    patient_name: 'Priya Deshmukh',
    uhid: 'RH-2026-001249',
    doctor_name: 'Dr. Neelima Joshi',
    status: 'pending',
    is_dispensed: false,
    medications: [
      { name: 'Aspirin 75mg', dosage: '75mg', frequency: 'OD', days: 30 },
      { name: 'Atorvastatin 20mg', dosage: '20mg', frequency: 'HS', days: 30 },
    ],
  },
  {
    id: 'rx-003',
    patient_name: 'Sanjay Patil',
    uhid: 'RH-2026-001253',
    doctor_name: 'Dr. Ramesh Kulkarni',
    status: 'pending',
    is_dispensed: false,
    medications: [
      { name: 'Ibuprofen 400mg', dosage: '400mg', frequency: 'BID', days: 5 },
      { name: 'Calcium + Vit D3', dosage: '500mg', frequency: 'OD', days: 30 },
    ],
  },
  {
    id: 'rx-004',
    patient_name: 'Vikram Sethi',
    uhid: 'RH-2026-001246',
    doctor_name: 'Dr. Arjun Rao',
    status: 'pending',
    is_dispensed: false,
    medications: [
      { name: 'Meropenem 1g', dosage: '1g', frequency: 'TID IV', days: 7 },
      { name: 'Normal Saline 500ml', dosage: '500ml', frequency: 'q8h', days: 3 },
    ],
  },
];

export const SEED_LAB = [
  {
    id: 'lab-001',
    patient_name: 'Ananya Krishnan',
    uhid: 'RH-2026-001245',
    test_names: ['CBC', 'Lipid Profile'],
    specimen: 'Blood',
    status: 'ORDERED',
    doctor_name: 'Dr. Meera Iyer',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lab-002',
    patient_name: 'Vikram Sethi',
    uhid: 'RH-2026-001246',
    test_names: ['Liver Function', 'Serum Creatinine'],
    specimen: 'Blood',
    status: 'SAMPLE_COLLECTED',
    doctor_name: 'Dr. Arjun Rao',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lab-003',
    patient_name: 'Rohit Malhotra',
    uhid: 'RH-2026-001248',
    test_names: ['CBC'],
    specimen: 'Blood',
    status: 'IN_DIAGNOSTICS',
    doctor_name: 'Dr. Suresh Pillai',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lab-004',
    patient_name: 'Meena Kuppuswamy',
    uhid: 'RH-2026-001251',
    test_names: ['Urine Routine', 'Culture'],
    specimen: 'Urine',
    status: 'VERIFIED',
    results: 'WBC 2-3/hpf · Culture negative',
    doctor_name: 'Dr. Meera Iyer',
    created_at: new Date().toISOString(),
  },
  {
    id: 'lab-005',
    patient_name: 'Karthik Venkatesh',
    uhid: 'RH-2026-001250',
    test_names: ['ABG', 'Troponin-I'],
    specimen: 'Blood',
    status: 'IN_DIAGNOSTICS',
    doctor_name: 'Dr. Arjun Rao',
    created_at: new Date().toISOString(),
  },
];

export const SEED_RADIOLOGY = [
  {
    id: 'rad-001',
    patient_name: 'Unknown Male (Trauma)',
    uhid: 'RH-2026-001252',
    modality: 'CT Scan',
    body_part: 'Brain · NCCT',
    priority: 'stat',
    doctor_name: 'Dr. Trauma Lead',
    radiologist: 'Dr. Imaging Lead',
    contrast: false,
    status: 'scheduled',
  },
  {
    id: 'rad-002',
    patient_name: 'Priya Deshmukh',
    uhid: 'RH-2026-001249',
    modality: 'X-Ray',
    body_part: 'Chest PA',
    priority: 'urgent',
    doctor_name: 'Dr. Neelima Joshi',
    radiologist: 'Dr. R. Balan',
    contrast: false,
    status: 'scheduled',
  },
  {
    id: 'rad-003',
    patient_name: 'Sanjay Patil',
    uhid: 'RH-2026-001253',
    modality: 'MRI',
    body_part: 'Left Knee',
    priority: 'routine',
    doctor_name: 'Dr. Ramesh Kulkarni',
    radiologist: 'Dr. Imaging Lead',
    contrast: false,
    status: 'completed',
    report_url: '/reports/mri-knee-patil.pdf',
  },
  {
    id: 'rad-004',
    patient_name: 'Ananya Krishnan',
    uhid: 'RH-2026-001245',
    modality: 'Ultrasound',
    body_part: 'Abdomen',
    priority: 'routine',
    doctor_name: 'Dr. Meera Iyer',
    radiologist: 'Dr. Softa USG',
    contrast: false,
    status: 'scheduled',
  },
  {
    id: 'rad-005',
    patient_name: 'Vikram Sethi',
    uhid: 'RH-2026-001246',
    modality: 'CT Scan',
    body_part: 'Chest · Contrast',
    priority: 'urgent',
    doctor_name: 'Dr. Arjun Rao',
    radiologist: 'Dr. Imaging Lead',
    contrast: true,
    status: 'scheduled',
  },
];

export const SEED_BILLS = [
  {
    id: 'bill-001',
    invoice_number: 'INV-2026-8841',
    patient_uhid: 'RH-2026-001245',
    patient_name: 'Ananya Krishnan',
    total_amount: 48500,
    paid_amount: 20000,
    status: 'partial',
    lines: [
      { item: 'Consultation · Dr. Meera Iyer', amount: 1500 },
      { item: 'Private Wing A · 3 days', amount: 36000 },
      { item: 'Pharmacy Rx', amount: 6200 },
      { item: 'Lab · CBC + Lipid', amount: 4800 },
    ],
  },
  {
    id: 'bill-002',
    invoice_number: 'INV-2026-8842',
    patient_uhid: 'RH-2026-001247',
    patient_name: 'Fatima Begum',
    total_amount: 2850,
    paid_amount: 0,
    status: 'unpaid',
    lines: [
      { item: 'OPD Consultation', amount: 800 },
      { item: 'Pharmacy Rx', amount: 650 },
      { item: 'Lab · CBC', amount: 1400 },
    ],
  },
  {
    id: 'bill-003',
    invoice_number: 'INV-2026-8843',
    patient_uhid: 'RH-2026-001246',
    patient_name: 'Vikram Sethi',
    total_amount: 186000,
    paid_amount: 50000,
    status: 'insurance_pending',
    lines: [
      { item: 'ICU · 2 days', amount: 90000 },
      { item: 'Ventilator support', amount: 45000 },
      { item: 'Pharmacy · Meropenem', amount: 28000 },
      { item: 'CT Chest Contrast', amount: 23000 },
    ],
  },
  {
    id: 'bill-004',
    invoice_number: 'INV-2026-8840',
    patient_uhid: 'RH-2026-001257',
    patient_name: 'Harish Gupta',
    total_amount: 3200,
    paid_amount: 3200,
    status: 'paid',
    lines: [
      { item: 'Cardiology consult', amount: 1200 },
      { item: 'ECG + Echo', amount: 2000 },
    ],
  },
];

export const SEED_INVENTORY = [
  {
    id: 'inv-001',
    item_code: 'MED-PCM-650',
    sku: 'MED-PCM-650',
    item_name: 'Paracetamol 650mg',
    category: 'Medicine',
    quantity_in_stock: 420,
    reorder_level: 100,
    unit_price: 2.5,
    vendor_name: 'Regal Medical Supplies',
    batch_number: 'B-PR26',
    expiry_date: '2027-08-01',
  },
  {
    id: 'inv-002',
    item_code: 'MED-MRP-1G',
    sku: 'MED-MRP-1G',
    item_name: 'Meropenem 1g',
    category: 'Medicine',
    quantity_in_stock: 18,
    reorder_level: 40,
    unit_price: 1850,
    vendor_name: 'Apex Pharma Distributors',
    batch_number: 'B-MR25',
    expiry_date: '2026-11-15',
  },
  {
    id: 'inv-003',
    item_code: 'CON-NS-500',
    sku: 'CON-NS-500',
    item_name: 'Normal Saline 500ml',
    category: 'Consumable',
    quantity_in_stock: 95,
    reorder_level: 120,
    unit_price: 45,
    vendor_name: 'Regal Medical Supplies',
    batch_number: 'B-NS26',
    expiry_date: '2027-01-20',
  },
  {
    id: 'inv-004',
    item_code: 'SUR-GLV-L',
    sku: 'SUR-GLV-L',
    item_name: 'Surgical Gloves (L)',
    category: 'Surgical',
    quantity_in_stock: 12,
    reorder_level: 50,
    unit_price: 18,
    vendor_name: 'SterileTech India',
    batch_number: 'B-GL26',
    expiry_date: '2028-03-01',
  },
  {
    id: 'inv-005',
    item_code: 'MED-ATR-20',
    sku: 'MED-ATR-20',
    item_name: 'Atorvastatin 20mg',
    category: 'Medicine',
    quantity_in_stock: 260,
    reorder_level: 80,
    unit_price: 12,
    vendor_name: 'Apex Pharma Distributors',
    batch_number: 'B-AT26',
    expiry_date: '2027-06-30',
  },
  {
    id: 'inv-006',
    item_code: 'SUR-SCT-3',
    sku: 'SUR-SCT-3',
    item_name: 'Vicryl Suture 3-0',
    category: 'Surgical',
    quantity_in_stock: 34,
    reorder_level: 25,
    unit_price: 220,
    vendor_name: 'SterileTech India',
    batch_number: 'B-VC26',
    expiry_date: '2028-12-01',
  },
];

export const SEED_POS = [
  {
    id: 'po-001',
    vendor_name: 'Apex Pharma Distributors',
    status: 'issued',
    total_cost: 92500,
    item_details: 'Meropenem 1g × 50',
  },
  {
    id: 'po-002',
    vendor_name: 'SterileTech India',
    status: 'issued',
    total_cost: 18000,
    item_details: 'Surgical Gloves (L) × 1000',
  },
];

export const SEED_STAFF = [
  ...regalDoctorsAsStaffRows(),
  {
    id: 'st-admin-001',
    employee_id: 'EMP-1001',
    display_name: 'Dr. Aishwarya D S',
    role: 'Admin',
    department: 'Administration',
    email: 'hospital@curasync.com',
    is_on_duty: true,
  },
  {
    id: 'st-002',
    employee_id: 'EMP-1002',
    display_name: 'Sneha Rao',
    role: 'Receptionist',
    department: 'Front Office',
    email: 'sneha.rao@regal.hospital',
    is_on_duty: true,
  },
  {
    id: 'st-003',
    employee_id: 'EMP-1003',
    display_name: 'Arun Menon',
    role: 'Biller',
    department: 'Finance',
    email: 'arun.menon@regal.hospital',
    is_on_duty: true,
  },
  {
    id: 'st-004',
    employee_id: 'EMP-1004',
    display_name: 'Nurse Deepa',
    role: 'Nurse',
    department: 'ICU',
    email: 'deepa.n@regal.hospital',
    is_on_duty: true,
  },
  {
    id: 'st-006',
    employee_id: 'EMP-1006',
    display_name: 'Pharmacist Vinod',
    role: 'Pharmacist',
    department: 'Pharmacy',
    email: 'vinod.p@regal.hospital',
    is_on_duty: true,
  },
  {
    id: 'st-007',
    employee_id: 'EMP-1007',
    display_name: 'Lab Tech Rekha',
    role: 'Lab Tech',
    department: 'Diagnostics',
    email: 'rekha.l@regal.hospital',
    is_on_duty: true,
  },
  {
    id: 'st-008',
    employee_id: 'EMP-1008',
    display_name: 'Procurement Officer Sam',
    role: 'Procurement',
    department: 'Supply Chain',
    email: 'sam.p@regal.hospital',
    is_on_duty: true,
  },
];

/** Vendor entities referenced by the ecosystem messaging composer. */
export const SEED_VENDORS = [
  { id: '11111111-1111-1111-1111-111111111111', name: 'MedSupply Ltd', category: 'Pharmaceuticals' },
  { id: '22222222-2222-2222-2222-222222222222', name: 'SurgicalPro India', category: 'Surgical Consumables' },
  { id: '33333333-3333-3333-3333-333333333333', name: 'LabEquip Solutions', category: 'Diagnostics Equipment' },
];

/** Sent communications history for the Ecosystem Messages workstation. */
export const SEED_ECOSYSTEM_MESSAGES = [
  {
    id: 'msg-001',
    recipient_type: 'Doctor',
    recipient_id: 'RH-D33',
    recipient_name: 'Dr. Santosh Shetty',
    category: 'Clinical Alert',
    priority: 'Urgent (Push Alarm)',
    subject: 'P1 Trauma — ED Bay 2',
    body: 'Unknown male, GCS 9, hypotensive. Immediate consult requested.',
    delivery_status: 'Delivered',
    target_app: 'Doctor App',
    created_at: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 'msg-002',
    recipient_type: 'Patient',
    recipient_id: 'RH-2026-001245',
    recipient_name: 'Ananya Krishnan',
    category: 'Billing & Discharge Notice',
    priority: 'Normal',
    subject: 'Final bill ready for settlement',
    body: 'Your consolidated discharge bill of ₹18,420 is ready at the cashier desk.',
    delivery_status: 'Read',
    target_app: 'Patients App',
    created_at: new Date(Date.now() - 120 * 60000).toISOString(),
  },
  {
    id: 'msg-003',
    recipient_type: 'Vendor',
    recipient_id: '11111111-1111-1111-1111-111111111111',
    recipient_name: 'MedSupply Ltd',
    category: 'Purchase Order Urgent Notice',
    priority: 'High',
    subject: 'Expedite PO-2026-4411 — ICU consumables',
    body: 'Critical stock-out risk on IV sets. Please confirm dispatch within 4 hours.',
    delivery_status: 'Delivered',
    target_app: 'Vendor App',
    created_at: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: 'msg-004',
    recipient_type: 'All',
    recipient_id: 'broadcast',
    recipient_name: 'All Ecosystem Apps',
    category: 'General Announcement',
    priority: 'Normal',
    subject: 'Regal Hospital fire drill — 4 PM today',
    body: 'Participate in the scheduled evacuation drill. OPD tokens will pause for 15 minutes.',
    delivery_status: 'Delivered',
    target_app: 'Broadcast All',
    created_at: new Date(Date.now() - 360 * 60000).toISOString(),
  },
];

export const SEED_EVENTS = [
  {
    id: 'ev-001',
    event_type: 'PATIENT_CHECKED_IN',
    source: 'REGAL HOSPITAL',
    severity: 'info',
    payload: { message: 'Fatima Begum checked in · Token GS-024' },
    created_at: new Date(Date.now() - 2 * 60000).toISOString(),
  },
  {
    id: 'ev-002',
    event_type: 'EMERGENCY_BYPASS_TRIGGERED',
    source: 'REGAL HOSPITAL',
    severity: 'critical',
    payload: { message: 'P1 Critical — Unknown Male (Trauma) · GCS 9' },
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
  },
  {
    id: 'ev-003',
    event_type: 'PRESCRIPTION_CREATED',
    source: 'DOCTOR APP',
    severity: 'info',
    payload: { message: 'Dr. Kavitha Nair issued Rx for Fatima Begum' },
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'ev-004',
    event_type: 'APPOINTMENT_BOOKED',
    source: 'PATIENT APP',
    severity: 'info',
    payload: { message: 'Priya Deshmukh booked Cardiology slot CARD-012' },
    created_at: new Date(Date.now() - 22 * 60000).toISOString(),
  },
  {
    id: 'ev-005',
    event_type: 'PURCHASE_ORDER_CREATED',
    source: 'REGAL HOSPITAL',
    severity: 'warning',
    payload: { message: 'PO issued to Apex Pharma · Meropenem 1g × 50' },
    created_at: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'ev-006',
    event_type: 'SHIPMENT_DISPATCHED',
    source: 'VENDOR APP',
    severity: 'info',
    payload: { message: 'SterileTech dispatched Surgical Gloves PO-002' },
    created_at: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: 'ev-007',
    event_type: 'LAB_RESULT_PUBLISHED',
    source: 'REGAL HOSPITAL',
    severity: 'info',
    payload: { message: 'Urine culture verified for Meena Kuppuswamy' },
    created_at: new Date(Date.now() - 70 * 60000).toISOString(),
  },
];

export const OPD_HOURLY = [4, 8, 14, 22, 28, 32, 30, 26, 18, 12, 8, 5];
