var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/hospital/billing/radiology-charges/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1iv1lle._.js")
R.c("server/chunks/ssr/0yz0_next_dist_1a-4c9q._.js")
R.c("server/chunks/ssr/0yz0_next_dist_esm_build_templates_app-page_051ndke.js")
R.c("server/chunks/ssr/[root-of-the-server]__14g52h1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__03qfu_z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__08g6l4k._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_0a70a9d._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_0e9exsp._.js")
R.c("server/chunks/ssr/0yz0_next_dist_client_components_builtin_unauthorized_18vk5b5.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_app_global-error_tsx_1n68bqr._.js")
R.c("server/chunks/ssr/OneDrive_Desktop_caresync_curasync_0o70gfr._.js")
R.c("server/chunks/ssr/0_f0_server_app_hospital_billing_radiology-charges_page_actions_0gbf7ya.js")
R.m(13698)
module.exports=R.m(13698).exports
